"""add_ai_usage_log

Revision ID: 19fcb1985d47
Revises: 935fe9bcc962
Create Date: 2026-05-16 10:17:33.051421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19fcb1985d47'
down_revision = '935fe9bcc962'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('num_questions', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('game_participants', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.drop_constraint('game_sessions_host_id_fkey', 'game_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'game_sessions', 'users', ['host_id'], ['id'], ondelete='CASCADE')
    op.alter_column('player_answers', 'answered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_answers', 'answered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-07 18:35:58.635418+00'::timestamp with time zone"),
               existing_nullable=False)
    # op.drop_constraint(None, 'game_sessions', type_='foreignkey')
    # op.create_foreign_key('game_sessions_host_id_fkey', 'game_sessions', 'users', ['host_id'], ['id'])
    op.alter_column('game_participants', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-07 18:35:58.635418+00'::timestamp with time zone"),
               existing_nullable=False)
    op.drop_table('ai_usage_logs')
    # ### end Alembic commands ###
