"""init_quiz_and_game_tables

Revision ID: 935fe9bcc962
Revises: d03213e3a658
Create Date: 2026-05-07 18:30:14.642109
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '935fe9bcc962'
down_revision = 'd03213e3a658'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quizzes_owner', 'quizzes', ['owner_id'], unique=False)
    op.create_index('idx_quizzes_public', 'quizzes', ['is_public'], unique=False, postgresql_where=sa.text('is_public = true'))
    op.create_table('game_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quiz_id', sa.Uuid(), nullable=False),
    sa.Column('host_id', sa.Uuid(), nullable=False),
    sa.Column('room_code', sa.String(length=6), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_question_idx', sa.SmallInteger(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('waiting', 'in_progress', 'finished')", name='chk_session_status'),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_code')
    )
    op.create_index('idx_sessions_active', 'game_sessions', [sa.text('status'), sa.text('created_at DESC')], unique=False, postgresql_where=sa.text("status IN ('waiting', 'in_progress')"))
    op.create_index('idx_sessions_host', 'game_sessions', ['host_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quiz_id', sa.Uuid(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('time_limit_secs', sa.SmallInteger(), nullable=False),
    sa.Column('points', sa.SmallInteger(), nullable=False),
    sa.Column('order_index', sa.SmallInteger(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("question_type IN ('multiple_choice', 'true_false')", name='chk_question_type'),
    sa.CheckConstraint('order_index >= 0', name='chk_order_index'),
    sa.CheckConstraint('points > 0', name='chk_points'),
    sa.CheckConstraint('time_limit_secs BETWEEN 5 AND 120', name='chk_time_limit'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_questions_quiz', 'questions', ['quiz_id', 'order_index'], unique=False)
    op.create_table('answer_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('order_index >= 0', name='chk_option_order'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_options_question', 'answer_options', ['question_id'], unique=False)
    op.create_table('game_participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=True),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_participants_guest_name', 'game_participants', ['session_id', 'display_name'], unique=True)
    op.create_index('idx_participants_session', 'game_participants', ['session_id'], unique=False)
    op.create_index('idx_participants_user_session', 'game_participants', ['session_id', 'user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_table('player_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('selected_option', sa.Uuid(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('score_earned', sa.Integer(), nullable=False),
    sa.Column('answer_time_ms', sa.Integer(), nullable=False),
    sa.Column('answered_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['game_participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['selected_option'], ['answer_options.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_id', 'question_id', name='uq_player_answers_participant_question')
    )
    op.create_index('idx_answers_participant', 'player_answers', ['participant_id'], unique=False)
    op.create_index('idx_answers_question', 'player_answers', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_answers_question', table_name='player_answers')
    op.drop_index('idx_answers_participant', table_name='player_answers')
    op.drop_table('player_answers')
    op.drop_index('idx_participants_user_session', table_name='game_participants', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('idx_participants_session', table_name='game_participants')
    op.drop_index('idx_participants_guest_name', table_name='game_participants')
    op.drop_table('game_participants')
    op.drop_index('idx_options_question', table_name='answer_options')
    op.drop_table('answer_options')
    op.drop_index('idx_questions_quiz', table_name='questions')
    op.drop_table('questions')
    op.drop_index('idx_sessions_host', table_name='game_sessions')
    op.drop_index('idx_sessions_active', table_name='game_sessions', postgresql_where=sa.text("status IN ('waiting', 'in_progress')"))
    op.drop_table('game_sessions')
    op.drop_index('idx_quizzes_public', table_name='quizzes', postgresql_where=sa.text('is_public = true'))
    op.drop_index('idx_quizzes_owner', table_name='quizzes')
    op.drop_table('quizzes')
    # ### end Alembic commands ###
